version: "3"
services:
  bloglist:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TEST_MONGODB_URI=${TEST_MONGODB_URI}
      - BEPORT=3002
      - PORT=3000
  nginx:
    image: nginx
    ports:
      - 90:90
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bloglist