name: Periodic Health Check

on:
  schedule:
    - cron: "0 12 * * *" # Runs once a day at mid-day

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://bloglist-cjpf.onrender.com/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
      - name: Site Alive
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Website is Alive!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Site Dead
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Website Down!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
